[[redirects]]
  from = "/groups"
  to = "https://durhamuniversity-my.sharepoint.com/:x:/g/personal/wdhm38_durham_ac_uk/IQC6VcCXTM4zSI5CpWBJDj9uAdrmhJLgugTBYefuw8X9x5U?e=TLydHm"
  status = 200
  force = true
